### ISSUE TITLE
Memory profiling of the pipeline

### ISSUE THREAD

**Issue by gidili** [MetaCell/minian#69]
Generate some kind of curve that represents memory consumption - with a breakdown of steps

**Comment by zsinnema** [comment]
first run on Raymond dataset with min 64M and max 256M chunksize. Memory usage: VmPeak: 32684760 kB
step 73 is the one consuming the most memory and time
```
%%time
generate_videos(
    minian, varr, dpath, param_save_minian['fname'] + ".mp4", scale='auto')
%%time
generate_videos(
    minian, varr, dpath, param_save_minian['fname'] + ".mp4", scale='auto')
generating traces
[########################################] | 100% Completed |  7.4s
[########################################] | 100% Completed |  1min 45.9s
writing videos
[########################################] | 100% Completed | 50.4s
[########################################] | 100% Completed |  1min 47.7s
[########################################] | 100% Completed | 52min 26.5s
[########################################] | 100% Completed | 55min  1.1s
concatenating results
CPU times: user 1h 12min 42s, sys: 26min 27s, total: 1h 39min 9s
Wall time: 1h 57min 3s
'/disk2/opt/projects/metacell/minian/bucket/minian-datasets/RaymondWC_DataSet/minian.mp4'
```

**Comment by zsinnema** [comment]
chunksize set to 16 will cause the demo dataset not to finish. stops at step 52 (first of first temporal update) 
high memory usage, swap usage (>42G)

**Comment by zsinnema** [comment]
when I run the pipeline using cgmemtime profiler (https://github.com/gsauthof/cgmemtime) there is no real difference between chunk shape 64M and 256M

```
64 M
Child high-water RSS                    :   13762104 KiB
Recursive and acc. high-water RSS+CACHE :   15446216 KiB

256 M
Child high-water RSS                    :   13441748 KiB
Recursive and acc. high-water RSS+CACHE :   15372824 KiB
```

total memory used by parent and child processes: 27.5G

**Comment by zsinnema** [comment]
The Raymond dataset on a 16G machine without any swap crashes with out of memory error
```
creating parallel schedule
computing ROIs
[###########                             ] | 28% Completed |  2min 39.0s
/home/ubuntu/miniconda3/envs/minian/lib/python3.8/site-packages/dask/array/routines.py:264: PerformanceWarning: Increasing number of chunks by factor of 12
  intermediate = blockwise(
Traceback (most recent call last):
  File "pipeline.py", line 292, in <module>
    A, C, b, f = initialize(Y, seeds_mrg[seeds_mrg['mask_mrg']], **param_initialize)
  File "/home/ubuntu/minian/minian/initialization.py", line 311, in initialize
    res_ls = dask.compute(res_ls)[0]
  File "/home/ubuntu/miniconda3/envs/minian/lib/python3.8/site-packages/dask/base.py", line 437, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/ubuntu/miniconda3/envs/minian/lib/python3.8/site-packages/dask/threaded.py", line 76, in get
    results = get_async(
  File "/home/ubuntu/miniconda3/envs/minian/lib/python3.8/site-packages/dask/local.py", line 486, in get_async
    raise_exception(exc, tb)
  File "/home/ubuntu/miniconda3/envs/minian/lib/python3.8/site-packages/dask/local.py", line 316, in reraise
    raise exc
  File "/home/ubuntu/miniconda3/envs/minian/lib/python3.8/site-packages/dask/local.py", line 222, in execute_task
    result = _execute_task(task, data)
  File "/home/ubuntu/miniconda3/envs/minian/lib/python3.8/site-packages/dask/core.py", line 119, in _execute_task
    return func(*args2)
  File "/home/ubuntu/miniconda3/envs/minian/lib/python3.8/site-packages/dask/optimization.py", line 982, in __call__
    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
  File "/home/ubuntu/miniconda3/envs/minian/lib/python3.8/site-packages/dask/core.py", line 149, in get
    result = _execute_task(task, cache)
  File "/home/ubuntu/miniconda3/envs/minian/lib/python3.8/site-packages/dask/core.py", line 119, in _execute_task
    return func(*args2)
  File "/home/ubuntu/miniconda3/envs/minian/lib/python3.8/site-packages/numpy/lib/function_base.py", line 2091, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "/home/ubuntu/miniconda3/envs/minian/lib/python3.8/site-packages/numpy/lib/function_base.py", line 2157, in _vectorize_call
    res = self._vectorize_call_with_signature(func, args)
  File "/home/ubuntu/miniconda3/envs/minian/lib/python3.8/site-packages/numpy/lib/function_base.py", line 2217, in _vectorize_call_with_signature
    outputs = _create_arrays(broadcast_shape, dim_sizes,
  File "/home/ubuntu/miniconda3/envs/minian/lib/python3.8/site-packages/numpy/lib/function_base.py", line 1873, in _create_arrays
    arrays = tuple(np.empty(shape, dtype=dtype)
  File "/home/ubuntu/miniconda3/envs/minian/lib/python3.8/site-packages/numpy/lib/function_base.py", line 1873, in <genexpr>
    arrays = tuple(np.empty(shape, dtype=dtype)
MemoryError: Unable to allocate 46.7 MiB for an array with shape (720, 8501) and data type float64
```

**Comment by zsinnema** [comment]
Running demo movies on a 16G machine no swap with a chunk of 128M fails at writing videos step:
```
[#########                               ] | 23% Completed | 44.4sProcess ForkPoolWorker-39:
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/minian/lib/python3.8/multiprocessing/pool.py", line 131, in worker
    put((job, i, result))
  File "/home/ubuntu/miniconda3/envs/minian/lib/python3.8/multiprocessing/queues.py", line 368, in put
    self._writer.send_bytes(obj)
  File "/home/ubuntu/miniconda3/envs/minian/lib/python3.8/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/ubuntu/miniconda3/envs/minian/lib/python3.8/multiprocessing/connection.py", line 405, in _send_bytes
    self._send(buf)
  File "/home/ubuntu/miniconda3/envs/minian/lib/python3.8/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/minian/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ubuntu/miniconda3/envs/minian/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/miniconda3/envs/minian/lib/python3.8/multiprocessing/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/home/ubuntu/miniconda3/envs/minian/lib/python3.8/multiprocessing/queues.py", line 368, in put
    self._writer.send_bytes(obj)
  File "/home/ubuntu/miniconda3/envs/minian/lib/python3.8/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/ubuntu/miniconda3/envs/minian/lib/python3.8/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header)
  File "/home/ubuntu/miniconda3/envs/minian/lib/python3.8/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by zsinnema** [comment]
Running the modified (attached) pipeline.py produces an error with the latest pull from the dev branch from the CaiLab Minian git repo with the "Toy Dataset" generator.

```
estimating penalty parameter
computing subsetting matrix
fitting spatial matrix
[########################################] | 100% Completed |  2.3s
removing empty units
updating background
background terms are empty
normalizing result
<built-in function mul>, [0]
Traceback (most recent call last):
  File "pipeline_toy.py", line 380, in <module>
    cur_A, cur_b, cur_C, cur_f = update_spatial(
  File "/disk2/opt/projects/metacell/minian/minian/minian/cnmf.py", line 266, in update_spatial
    A_new.stack(spatial=["height", "width"]),
  File "/home/zoran/miniconda3/envs/minian/lib/python3.8/site-packages/xarray/core/dataarray.py", line 1741, in stack
    ds = self._to_temp_dataset().stack(dimensions, **dimensions_kwargs)
  File "/home/zoran/miniconda3/envs/minian/lib/python3.8/site-packages/xarray/core/dataset.py", line 3293, in stack
    result = result._stack_once(dims, new_dim)
  File "/home/zoran/miniconda3/envs/minian/lib/python3.8/site-packages/xarray/core/dataset.py", line 3242, in _stack_once
    stacked_var = exp_var.stack(**{new_dim: dims})
  File "/home/zoran/miniconda3/envs/minian/lib/python3.8/site-packages/xarray/core/variable.py", line 1406, in stack
    result = result._stack_once(dims, new_dim)
  File "/home/zoran/miniconda3/envs/minian/lib/python3.8/site-packages/xarray/core/variable.py", line 1373, in _stack_once
    new_data = reordered.data.reshape(new_shape)
  File "/home/zoran/miniconda3/envs/minian/lib/python3.8/site-packages/dask/array/core.py", line 1719, in reshape
    return reshape(self, shape)
  File "/home/zoran/miniconda3/envs/minian/lib/python3.8/site-packages/dask/array/reshape.py", line 169, in reshape
    missing_size = sanitize_index(x.size / reduce(mul, known_sizes, 1))
ZeroDivisionError: division by zero
```

**Comment by zsinnema** [comment]
[pipeline_toy.py.tar.gz](https://github.com/MetaCell/minian/files/4964356/pipeline_toy.py.tar.gz)
